# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
bioc_required: true
warnings_are_errors: true

r:
  - release
  - devel
  
apt_packages:
 - default-jre
 - default-jdk
 - libopenbabel-dev
 - libudunits2-dev
 
r_github_packages:
    - jasenfinch/mzAnnotation
 
notifications:
    email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'